theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/circle-opacity"  # Equinox logo in top left
    favicon: "_static/favicon.png"
    custom_dir: "docs/_overrides"  # Overriding part of the HTML

    # These additions are my own custom ones, having overridden a partial.
    twitter_name: "@_ecunningham_"
    twitter_url: "https://twitter.com/_ecunningham_"

site_name: generax
site_description: The documentation for the generax software library.
site_author: Eddie Cunningham
site_url: https://eddiecunningham.github.io/generax

repo_url: https://github.com/EddieCunningham/generax
repo_name: EddieCunningham/generax
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: true  # Don't allow warnings during the build process

extra_javascript:
    # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - include_exclude_files:
        include:
            - ".htaccess"
        exclude:
            - "_overrides"
            # - "examples/MNIST"
            # - "examples/bert_checkpoint.eqx"
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()
                    - import jaxtyping
                    - jaxtyping.set_array_name_format("array")

                selection:
                    inherited_members: true  # Allow looking up inherited methods
                rendering:
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: true  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4

nav:
    - 'index.md'
    - API:
        - Distributions:
            - 'api/distributions/distributions.md'
            - 'api/distributions/coupling.md'
            - 'api/distributions/flow_models.md'
        - BijectiveTransforms:
            - api/flows/base.md
            - api/flows/affine.md
            - api/flows/coupling.md
            - api/flows/ffjord.md
            - api/flows/nonlinearities.md
            - api/flows/compositions.md
        - NN:
            - api/nn/layers.md
            - api/nn/time_condition.md
            - api/nn/resnet_blocks.md
            - api/nn/resnet.md
            - api/nn/unet.md
        - Misc:
            - api/misc/trainer.md
    - Examples:
        - Notebooks:
            - Flow matching tutorial: 'notebooks/cnf.ipynb'
